export type CompanyStatus = "active" | "suspend";
export type CompanyEmail = {
  id: number;
  email: string;
  emailType: string;
  isPrimary: boolean;
  sortOrder: number;
};
export type CompanyPhone = {
  id: number;
  phone: string;
  phoneType: string;
  isPrimary: boolean;
  sortOrder: number;
};
export type CompanyAddress = {
  id: number;
  addressTypeId: number | null;
  addressTypeName: string | null;
  addressLine1: string;
  addressLine2: string | null;
  countryId: number | null;
  countryName: string | null;
  stateId: number | null;
  stateName: string | null;
  districtId: number | null;
  districtName: string | null;
  cityId: number | null;
  cityName: string | null;
  pincodeId: number | null;
  pincodeName: string | null;
  isDefault: boolean;
  sortOrder: number;
};
export type CompanyBankAccount = {
  id: number;
  bankNameId: number | null;
  bankName: string | null;
  accountType: string | null;
  accountNumber: string;
  holderName: string | null;
  ifsc: string | null;
  branch: string | null;
  isPrimary: boolean;
  sortOrder: number;
};
export type CompanySocialLink = {
  id: number;
  platform: string;
  url: string;
  status: "active" | "inactive";
  isActive: boolean;
  sortOrder: number;
};

export type CompanyRecord = {
  id: number;
  code: string;
  name: string;
  legalName: string | null;
  primaryPhone: string | null;
  primaryEmail: string | null;
  gstin: string | null;
  pan: string | null;
  msmeNo: string | null;
  msmeCategory: string | null;
  tanNo: string | null;
  tdsAvailable: boolean;
  tcsAvailable: boolean;
  website: string | null;
  description: string | null;
  logoPath: string | null;
  logoDarkPath: string | null;
  industryId: number | null;
  industryName: string | null;
  status: CompanyStatus;
  isActive: boolean;
  emails: CompanyEmail[];
  phones: CompanyPhone[];
  addresses: CompanyAddress[];
  bankAccounts: CompanyBankAccount[];
  socialLinks: CompanySocialLink[];
  createdAt: string;
  updatedAt: string;
};

export type CompanySaveInput = {
  code?: string | undefined;
  name: string;
  legalName?: string | null | undefined;
  gstin?: string | null | undefined;
  pan?: string | null | undefined;
  msmeNo?: string | null | undefined;
  msmeCategory?: string | null | undefined;
  tanNo?: string | null | undefined;
  tdsAvailable?: boolean | undefined;
  tcsAvailable?: boolean | undefined;
  website?: string | null | undefined;
  description?: string | null | undefined;
  logoPath?: string | null | undefined;
  logoDarkPath?: string | null | undefined;
  industryId?: number | null | undefined;
  industryName?: string | null | undefined;
  status?: CompanyStatus | undefined;
  isActive?: boolean | undefined;
  emails?: CompanyEmail[] | undefined;
  phones?: CompanyPhone[] | undefined;
  addresses?: CompanyAddress[] | undefined;
  bankAccounts?: CompanyBankAccount[] | undefined;
  socialLinks?: CompanySocialLink[] | undefined;
};

export type CompanyIndustryNameResolver = (industryId: number) => Promise<string | null>;
