/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deploy/cloudflare/demo/wrangler.jsonc --include-runtime=false deploy/cloudflare/demo/worker-configuration.d.ts` (hash: a8072b230ce56282b019bcd20f43dcdc)
interface __BaseEnv_Env {
	PLATFORM_DB: D1Database;
	TENANT_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
